language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - BITS=32
    SKIP_WINE_KNOWN_FAILURES=1

# The pywin32-219 installers for python 2.6 64bit are missing files.
# 64-bit for 2.7, 3.5 and 3.6 are tested with appveyor.

before_install:
  - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
  - sudo apt-get update
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - sudo apt-get install -y --force-yes wine
  - pip install coveralls
  - sh scripts/setup_tests_wine.sh

script:
  - sh scripts/run_tests_wine.sh

after_success:
  - pip install codecov
  - codecov
