build: false
shallow_clone: true
skip_branch_with_pr: true

environment:

  pythonunbuffered: "1"
  show_test_env: "1"

  matrix:
    - toxpy27: "C:/Python27-x64/python.exe"
      toxpy35: "C:/Python35-x64/python.exe"
      toxpy36: "C:/Python36-x64/python.exe"
    - toxpy27: "C:/Python27/python.exe"
      toxpy35: "C:/Python35/python.exe"
      toxpy36: "C:/Python36/python.exe"

matrix:
  fast_finish: true

cache:
  - C:\Users\appveyor\AppData\Local\pip\Cache -> appveyor-cache.txt

install:
  - ps: pip install --upgrade pip wheel
  - ps: pip install tox
test_script:
  - mkdir testruns
  - copy .coveragerc testruns
  - cd testruns
  - tox
on_success:
  - pip install codecov
  - codecov
